#!/bin/bash

# array of language codes
layouts=( $(xkb-switch -l) )

# represents index of current layout
current=1

for i in "${layouts[@]}"
do
	if [ "$i" = "$(xkb-switch)" ]
	then
		break
	fi
	((++current))
done

xkb-switch -s ${layouts[current-2]}
unset current
unset layouts
